export interface Curso {
  nome: string;
  tipo: string;
  area: string;
  link: string;
  descricao: string;
}

export const CURSOS_FMA: Curso[] = [
  {
    nome: "Filosofia, Política e Economia",
    tipo: "Pós-Graduação",
    area: "Ciências Sociais",
    link: "https://faculdademaratlantico.edu.br/pos-graduacao/filosofia-politica-e-economia/",
    descricao: "A Pós-Graduação em Filosofia, Política e Economia (FPE) é uma formação multidisciplinar que integra três áreas essenciais para compreender e atuar nos desafios do mundo contemporâneo. Inspirada em pro...",
  },
  {
    nome: "Segurança Pública",
    tipo: "Pós-Graduação",
    area: "Ciências Sociais",
    link: "https://faculdademaratlantico.edu.br/pos-graduacao/seguranca-publica/",
    descricao: "A Pós-Graduação em Segurança Pública é uma formação inovadora e pioneira no Brasil, voltada para profissionais que desejam atuar estrategicamente em um dos setores essenciais da sociedade. Com um enfo...",
  },
  {
    nome: "Sistemas políticos",
    tipo: "Curso Livre",
    area: "Ciências Sociais",
    link: "https://faculdademaratlantico.edu.br/curso-livre/sistemas-politicos/",
    descricao: "Curso que explora os diferentes sistemas políticos, formas de governo e instituições, oferecendo base crítica para analisar o Estado, o poder soberano e a governança contemporânea.",
  },
  {
    nome: "Certificação em Audiovisual",
    tipo: "Certificação",
    area: "Comunicação",
    link: "https://faculdademaratlantico.edu.br/certificacao/certificacao-audiovisual/",
    descricao: "A Certificação Audiovisual (CAV) é uma formação intensiva que une prática e mercado, ministrada por profissionais premiados do cinema, TV e streaming. O curso oferece aprendizado aplicado em todas as ...",
  },
  {
    nome: "Direito Civil",
    tipo: "Pós-Graduação",
    area: "Direito",
    link: "https://faculdademaratlantico.edu.br/pos-graduacao/direito-civil",
    descricao: "A Pós-Graduação em Responsabilidade Civil, Direito do Consumidor e Contratos é um programa robusto e interdisciplinar, que busca oferecer uma formação especializada e prática para advogados interessad...",
  },
  {
    nome: "Direito Criminal",
    tipo: "Pós-Graduação",
    area: "Direito",
    link: "https://faculdademaratlantico.edu.br/pos-graduacao/direito-criminal/",
    descricao: "Se você busca uma especialização que vá além do básico e o prepare para os desafios reais do Direito Criminal, nossa Pós-Graduação Lato Sensu em Direito Criminal foi criada para você.",
  },
  {
    nome: "Direito de Família e Sucessões",
    tipo: "Pós-Graduação",
    area: "Direito",
    link: "https://faculdademaratlantico.edu.br/pos-graduacao/direito-de-familia-e-sucessoes/",
    descricao: "A Pós-Graduação em Direito de Família e Sucessões é um curso voltado para profissionais que desejam se especializar em uma das áreas mais desafiadoras e humanas do Direito. Este programa proporciona u...",
  },
  {
    nome: "Direito Digital",
    tipo: "Pós-Graduação",
    area: "Direito",
    link: "https://faculdademaratlantico.edu.br/pos-graduacao/direito-digital/",
    descricao: "O Direito Digital emerge como uma disciplina essencial neste primeiro quarto do século XXI, período em que as Novas Tecnologias de Informação e Comunicação (NTIC) transformam substancialmente a maneir...",
  },
  {
    nome: "Direito Eleitoral",
    tipo: "Pós-Graduação",
    area: "Direito",
    link: "https://faculdademaratlantico.edu.br/pos-graduacao/direito-eleitoral/",
    descricao: "A Pós-Graduação em Direito Eleitoral é o passo ideal para você que deseja se destacar em um dos campos mais dinâmicos e relevantes do Direito. O curso foi cuidadosamente projetado para transformar pro...",
  },
  {
    nome: "Direito Empresarial",
    tipo: "Pós-Graduação",
    area: "Direito",
    link: "https://faculdademaratlantico.edu.br/pos-graduacao/direito-empresarial/",
    descricao: "A Pós-Graduação Lato Sensu em Direito Empresarial foi cuidadosamente estruturada para capacitar profissionais do Direito a atuarem com excelência no ambiente corporativo, um dos setores mais dinâmicos...",
  },
  {
    nome: "Direito Médico e da Saúde",
    tipo: "Pós-Graduação",
    area: "Direito",
    link: "https://faculdademaratlantico.edu.br/pos-graduacao/direito-medico-e-da-saude/",
    descricao: "O Curso de Pós-Graduação Lato Sensu em Direito Médico e da Saúde é uma oportunidade única para advogados que desejam aprofundar seus conhecimentos na interface entre o Direito e o universo da saúde.",
  },
  {
    nome: "Direito Trabalhista",
    tipo: "Pós-Graduação",
    area: "Direito",
    link: "https://faculdademaratlantico.edu.br/pos-graduacao/direito-trabalhista/",
    descricao: "O curso de Pós-Graduação Lato Sensu em Direito do Trabalho visa capacitar profissionais de forma especializada, ética e atualizada nas complexidades desse campo jurídico.",
  },
  {
    nome: "Direito Tributário",
    tipo: "Pós-Graduação",
    area: "Direito",
    link: "https://faculdademaratlantico.edu.br/pos-graduacao/direito-tributario/",
    descricao: "A Pós-Graduação Lato Sensu em Direito Tributário é uma iniciativa acadêmica voltada para a especialização de advogados e outros profissionais da área jurídica, com o objetivo de proporcionar uma compr...",
  },
  {
    nome: "Fundamentos da responsabilidade civil e direito contratual",
    tipo: "Curso Livre",
    area: "Direito",
    link: "https://faculdademaratlantico.edu.br/curso-livre/fundamentos-direito-contratual/",
    descricao: "Curso voltado a profissionais e estudantes de Direito que desejam dominar os fundamentos da responsabilidade civil e do direito contratual, com abordagem prática sobre princípios, tipos de danos e apl...",
  },
  {
    nome: "A Didática e Pedagogia para Professores",
    tipo: "Curso Livre",
    area: "Educação e Família",
    link: "https://faculdademaratlantico.edu.br/curso-livre/a-didatica-e-pedagogia-para-professores/",
    descricao: "Curso que capacita educadores nos fundamentos teóricos e práticos da docência, abordando pedagogia, planejamento de aulas, autoridade educativa e avaliação da aprendizagem.",
  },
  {
    nome: "A instituição da família e o matrimônio",
    tipo: "Curso Livre",
    area: "Educação e Família",
    link: "https://faculdademaratlantico.edu.br/curso-livre/a-instituicao-da-familia-e-o-matrimonio/",
    descricao: "Curso que analisa a evolução histórica, social e cultural da família e do matrimônio, destacando seus fundamentos, valores e desafios nas sociedades contemporâneas.",
  },
  {
    nome: "Certificação de Professores",
    tipo: "Certificação",
    area: "Educação e Família",
    link: "https://faculdademaratlantico.edu.br/certificacao/certificacao-de-professores/",
    descricao: "A Certificação de Professores forma educadores a partir de uma visão integral do ser humano, unindo fundamentos filosóficos, psicológicos e pedagógicos à prática docente. Com enfoque personalista e in...",
  },
  {
    nome: "Certificação em Educação Personalizada",
    tipo: "Certificação",
    area: "Educação e Família",
    link: "https://faculdademaratlantico.edu.br/certificacao/educacao-personalizada/",
    descricao: "A Certificação em Educação Personalizada forma educadores capazes de promover o desenvolvimento integral da pessoa humana, unindo fundamentos filosóficos, antropológicos e práticos em uma abordagem ce...",
  },
  {
    nome: "Ciências da Família",
    tipo: "Pós-Graduação",
    area: "Educação e Família",
    link: "https://faculdademaratlantico.edu.br/pos-graduacao/ciencias-da-familia/",
    descricao: "A Pós-Graduação em Ciências da Família é uma formação interdisciplinar que busca compreender e abordar os desafios enfrentados pelas famílias na sociedade contemporânea. O curso oferece uma visão abra...",
  },
  {
    nome: "Formação em Orientação Familiar",
    tipo: "Curso Livre",
    area: "Educação e Família",
    link: "https://faculdademaratlantico.edu.br/curso-livre/formacao-em-orientacao-familiar/",
    descricao: "A Formação em Orientação Familiar capacita profissionais para compreender e acompanhar famílias a partir de uma visão integral da pessoa, unindo fundamentos da psicologia, filosofia e teologia na prom...",
  },
  {
    nome: "Gestão Escolar",
    tipo: "Pós-Graduação",
    area: "Educação e Família",
    link: "https://faculdademaratlantico.edu.br/mba/gestao-escolar/",
    descricao: "O MBA em Gestão Escolar capacita gestores escolares a alinhar ética, liderança e inclusão com inovação e tecnologia. Forma profissionais aptos a lidar com processos administrativos, marketing educacio...",
  },
  {
    nome: "Lar, Doce Lar",
    tipo: "Curso Livre",
    area: "Educação e Família",
    link: "https://faculdademaratlantico.edu.br/curso-livre/lar-doce-lar/",
    descricao: "O curso “Lar, Doce Lar: Casamento, Família e Filhos” aborda de forma integrada os aspectos emocionais, éticos e práticos do casamento e da vida familiar, explorando temas como diálogo conjugal, educaç...",
  },
  {
    nome: "Matemática de Singapura",
    tipo: "Curso Livre",
    area: "Educação e Família",
    link: "https://faculdademaratlantico.edu.br/curso-livre/matematica-de-singapura/",
    descricao: "O curso explora a Matemática de Singapura, unindo teoria e prática para desenvolver o raciocínio lógico e a compreensão conceitual dos alunos.",
  },
  {
    nome: "Método Fônico",
    tipo: "Curso Livre",
    area: "Educação e Família",
    link: "https://faculdademaratlantico.edu.br/curso-livre/alfabetizacao-por-metodo-fonico/",
    descricao: "O curso Alfabetização por Método Fônico oferece uma formação teórico-prática sobre o processo de aquisição da leitura e da escrita, fundamentada no desenvolvimento da consciência fonológica e na aprop...",
  },
  {
    nome: "Antropologia Filosófica",
    tipo: "Pós-Graduação",
    area: "Filosofia",
    link: "https://faculdademaratlantico.edu.br/pos-graduacao/antropologia-filosofica/",
    descricao: "A Pós-Graduação em Antropologia Filosófica é um curso que explora profundamente o ser humano, integrando perspectivas religiosas, científicas, psicológicas e filosóficas sob a ótica da filosofia cláss...",
  },
  {
    nome: "Filosofia Aplicada",
    tipo: "Pós-Graduação",
    area: "Filosofia",
    link: "https://faculdademaratlantico.edu.br/pos-graduacao/filosofia-aplicada/",
    descricao: "Ao se debruçar sobre o estudo da natureza humana, a Filosofia busca compreender aspectos fundamentais da existência, como origem, propósito, liberdade e consciência. Os estudos filosóficos promovem o ...",
  },
  {
    nome: "Filosofia Geral",
    tipo: "Pós-Graduação",
    area: "Filosofia",
    link: "https://faculdademaratlantico.edu.br/pos-graduacao/filosofia-geral/",
    descricao: "A Pós-Graduação em Filosofia Geral é uma jornada instigante pelo vasto universo do pensamento humano, estruturada para aprofundar o entendimento sobre as questões fundamentais que moldaram nossa visão...",
  },
  {
    nome: "Filosofia Patrística e Medieval",
    tipo: "Pós-Graduação",
    area: "Filosofia",
    link: "https://faculdademaratlantico.edu.br/pos-graduacao/filosofia-patristica-e-medieval/",
    descricao: "A Pós-Graduação em Filosofia Patrística e Medieval é um convite a explorar as origens do pensamento filosófico e teológico que moldaram a tradição ocidental cristã. O curso oferece uma formação aprofu...",
  },
  {
    nome: "Fundamentos da Filosofia",
    tipo: "Curso Livre",
    area: "Filosofia",
    link: "https://faculdademaratlantico.edu.br/curso-livre/fundamentos-da-filosofia/",
    descricao: "Curso introdutório à filosofia clássica que aborda metafísica, lógica e metodologia, com foco na tradição aristotélico-tomista e no desenvolvimento do pensamento crítico.",
  },
  {
    nome: "Certificação em IA",
    tipo: "Certificação",
    area: "Negócios",
    link: "https://faculdademaratlantico.edu.br/certificacao/certificacao-em-ia/",
    descricao: "Criada para revolucionar a forma como você trabalha, a Certificação em IA da Faculdade Mar Atlântico oferece um aprendizado prático e exclusivo, desenvolvido por Rica Barros, fundador da Pareto (6ª ma...",
  },
  {
    nome: "Certificação em Marketing Digital & Vendas",
    tipo: "Certificação",
    area: "Negócios",
    link: "https://faculdademaratlantico.edu.br/certificacao/marketing-digital-e-vendas/",
    descricao: "A Certificação em Marketing Digital e Vendas integra fundamentos filosóficos e humanísticos com as estratégias mais atuais do mercado digital. Unindo reflexão ética e pensamento analítico, o curso for...",
  },
  {
    nome: "AI Leader",
    tipo: "Pós-Graduação",
    area: "Negócios",
    link: "https://faculdademaratlantico.edu.br/pos-graduacao/ai-leader/",
    descricao: "O programa definitivo para líderes da nova era da Inteligência Artificial Transforme-se em um líder estratégico em IA e destaque-se no mercado com este MBA exclusivo - reconhecido pelo MEC e desenvolv...",
  },
  {
    nome: "Formação ABA+",
    tipo: "Curso Livre",
    area: "Psicologia",
    link: "https://faculdademaratlantico.edu.br/certificacao/formacao-aba/",
    descricao: "O curso de Certificação para Aplicadores ABA forma profissionais para atuar com pessoas com Transtorno do Espectro Autista (TEA), unindo fundamentos da psicologia, neurociência e educação. Com base ci...",
  },
  {
    nome: "Psicologia do Marketing e Liderança",
    tipo: "Pós-Graduação",
    area: "Psicologia",
    link: "https://faculdademaratlantico.edu.br/pos-graduacao/psicologia-do-marketing-e-lideranca/",
    descricao: "A Pós em Psicologia do Marketing e Liderança une filosofia tomista, psicologia e neurociência para formar líderes éticos e estratégicos. O curso aborda virtudes, temperamentos, decisão, influência soc...",
  },
  {
    nome: "Interfaces da Psicologia",
    tipo: "Pós-Graduação",
    area: "Psicologia",
    link: "https://faculdademaratlantico.edu.br/pos-graduacao/interfaces-da-psicologia/",
    descricao: "A Pós-Graduação em Interfaces da Psicologia integra os fundamentos da psicologia com as ciências da mente, oferecendo uma visão ampla e interdisciplinar do comportamento humano. O curso aborda temas c...",
  },
  {
    nome: "Neuropsicologia",
    tipo: "Pós-Graduação",
    area: "Psicologia",
    link: "https://faculdademaratlantico.edu.br/pos-graduacao/neuropsicologia/",
    descricao: "O Programa de Pós-Graduação em Neuropsicologia foi desenvolvido para atender à crescente demanda do mercado por neuropsicólogos altamente qualificados. Este curso oferece uma formação completa e práti...",
  },
  {
    nome: "Psicologia Clínica",
    tipo: "Pós-Graduação",
    area: "Psicologia",
    link: "https://faculdademaratlantico.edu.br/pos-graduacao/psicologia-clinica/",
    descricao: "A Pós-Graduação em Psicologia Clínica capacita profissionais para atuar com eficácia na saúde mental, com uma abordagem multidisciplinar. O curso oferece ferramentas teóricas e práticas para a psicote...",
  },
  {
    nome: "Psicologia e Espiritualidade",
    tipo: "Pós-Graduação",
    area: "Psicologia",
    link: "https://faculdademaratlantico.edu.br/pos-graduacao/psicologia-e-espiritualidade/",
    descricao: "Pós-Graduação em Psicologia e Espiritualidade oferece uma abordagem interdisciplinar que integra os fundamentos metafísicos da realidade com os principais conceitos da psicologia, especialmente sob a ...",
  },
  {
    nome: "Psicologia Familiar",
    tipo: "Pós-Graduação",
    area: "Psicologia",
    link: "https://faculdademaratlantico.edu.br/pos-graduacao/psicologia-familiar/",
    descricao: "O Programa de Pós-Graduação em Psicologia Familiar foi desenvolvido para capacitar profissionais da área de saúde mental a atender de forma especializada as variadas demandas relacionadas à dinâmica f...",
  },
  {
    nome: "Psicologia Organizacional",
    tipo: "Pós-Graduação",
    area: "Psicologia",
    link: "https://faculdademaratlantico.edu.br/pos-graduacao/psicologia-organizacional/",
    descricao: "A Psicologia Organizacional surgiu no início do século XX, impulsionada pela necessidade de aumentar a produtividade nas indústrias. Com o tempo, a área evoluiu para incluir não apenas a eficiência pr...",
  },
  {
    nome: "Psicopedagogia",
    tipo: "Pós-Graduação",
    area: "Psicologia",
    link: "https://faculdademaratlantico.edu.br/pos-graduacao/psicopedagogia/",
    descricao: "A pós-graduação em Psicopedagogia é voltada para profissionais interessados em aprofundar o conhecimento sobre os processos de aprendizagem e nas técnicas de intervenção para superar dificuldades educ...",
  },
  {
    nome: "Suplementação & Nutrição na Saúde Mental",
    tipo: "Curso Livre",
    area: "Psicologia",
    link: "https://faculdademaratlantico.edu.br/pos-graduacao/suplementacao-e-nutricao-na-saude-mental/",
    descricao: "A Pós-Graduação em Suplementação e Nutrição na Saúde Mental integra nutrição, neurociência e psiquiatria para compreender como a alimentação influencia o humor, o comportamento e a saúde cerebral. Com...",
  },
  {
    nome: "TEA",
    tipo: "Pós-Graduação",
    area: "Psicologia",
    link: "https://faculdademaratlantico.edu.br/pos-graduacao/transtorno-do-espectro-autista-tea-infantil/",
    descricao: "A Pós-Graduação em TEA Infantil forma profissionais para compreender e atuar no autismo com base em fundamentos filosóficos, psicológicos e neurocientíficos, unindo teoria, prática e ética em uma abor...",
  },
  {
    nome: "O Poder da Simbólica",
    tipo: "Curso Livre",
    area: "Simbólica",
    link: "https://faculdademaratlantico.edu.br/curso-livre/o-poder-da-simbolica/",
    descricao: "O curso O Poder da Simbólica, de Italo Marsili, conduz o aluno a compreender o sentido profundo dos símbolos e arquétipos que orientam a vida humana, unindo psicologia, filosofia e espiritualidade em ...",
  },
  {
    nome: "Símbólica e Arte",
    tipo: "Curso Livre",
    area: "Simbólica",
    link: "https://faculdademaratlantico.edu.br/curso-livre/simbolica-e-arte/",
    descricao: "O curso Simbólica & Arte oferece uma imersão teórico-vivencial na linguagem simbólica das obras de arte, revelando nelas caminhos de autoconhecimento, propósito e transcendência.",
  },
  {
    nome: "Simbólica e Psicologia",
    tipo: "Curso Livre",
    area: "Simbólica",
    link: "https://faculdademaratlantico.edu.br/curso-livre/simbolica-e-psicologia/",
    descricao: "O curso Simbólica & Psicologia integra as principais escolas terapêuticas a uma leitura simbólica da alma humana, oferecendo um método claro para compreender e orientar processos de transformação pess...",
  },
  {
    nome: "Fundamentos da Interpretação Bíblica",
    tipo: "Curso Livre",
    area: "Teologia",
    link: "https://faculdademaratlantico.edu.br/curso-livre/fundamentos-da-interpretacao-biblica/",
    descricao: "O curso livre Fundamentos da Interpretação Bíblica oferece uma introdução prática e teológica à leitura das Sagradas Escrituras, abordando temas como a natureza da Bíblia, a Revelação divina e os prin...",
  },
  {
    nome: "Sagradas Escrituras",
    tipo: "Pós-Graduação",
    area: "Teologia",
    link: "https://faculdademaratlantico.edu.br/pos-graduacao/sagradas-escrituras/",
    descricao: "A pós-graduação em Sagradas Escrituras oferece formação profunda sobre a Bíblia, unindo estudo teológico, histórico e linguístico. Com base em Hebraico, Grego e hermenêutica, o curso analisa o Antigo ...",
  },
  {
    nome: "Teologia Dogmática",
    tipo: "Pós-Graduação",
    area: "Teologia",
    link: "https://faculdademaratlantico.edu.br/pos-graduacao/teologia-dogmatica/",
    descricao: "A pós-graduação em Teologia Dogmática oferece uma formação sólida para quem deseja aprofundar-se nas doutrinas centrais da fé cristã. Esse curso é estruturado para explorar temas essenciais sobre Deus...",
  },
  {
    nome: "Teologia Espiritual",
    tipo: "Pós-Graduação",
    area: "Teologia",
    link: "https://faculdademaratlantico.edu.br/pos-graduacao/teologia-espiritual/",
    descricao: "A pós-graduação em Teologia Espiritual: Ascética e Mística/Direção Espiritual oferece uma formação completa para aqueles que desejam aprofundar-se na vida interior e no ofício de direção espiritual. E...",
  },
  {
    nome: "Teologia Moral",
    tipo: "Pós-Graduação",
    area: "Teologia",
    link: "https://faculdademaratlantico.edu.br/pos-graduacao/teologia-moral/",
    descricao: "A pós-graduação em Teologia Moral oferece uma visão profunda e abrangente sobre a evolução da moralidade dentro da tradição cristã, explorando o desenvolvimento histórico e os conceitos fundamentais q...",
  }
];
